spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://postgresdb:5432/mizuyaribotdb
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
line:
  bot:
    channelToken: xxx
    channelSecret: xxx
    handler:
      path: /callback

# logging:
#   level:
#     org.hibernate: DEBUG
