
/* Drop Tables */

DROP TABLE IF EXISTS WATERING;
DROP TABLE IF EXISTS LINE_USER;




/* Create Tables */

CREATE TABLE LINE_USER
(
	LINE_USER_ID VARCHAR(100) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (LINE_USER_ID)
) WITHOUT OIDS;


CREATE TABLE WATERING
(
	WATERING_ID BIGINT NOT NULL,
	LINE_USER_ID VARCHAR(100) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	PLANT_NAME VARCHAR(100),
	FREQUENCY_IN_DAYS INT,
	NEXT_DATE DATE,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (WATERING_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE WATERING
	ADD CONSTRAINT FK_WATERING_USER FOREIGN KEY (LINE_USER_ID)
	REFERENCES LINE_USER (LINE_USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE LINE_USER IS 'ユーザー';
COMMENT ON COLUMN LINE_USER.LINE_USER_ID IS 'ユーザーID';
COMMENT ON COLUMN LINE_USER.STATUS IS 'ステータス';
COMMENT ON COLUMN LINE_USER.CREATED_AT IS '作成日時';
COMMENT ON COLUMN LINE_USER.UPDATED_AT IS '更新日時';

COMMENT ON TABLE WATERING IS '水やり';
COMMENT ON COLUMN WATERING.WATERING_ID IS '水やりID';
COMMENT ON COLUMN WATERING.LINE_USER_ID IS 'ユーザーID';
COMMENT ON COLUMN WATERING.STATUS IS 'ステータス';
COMMENT ON COLUMN WATERING.PLANT_NAME IS '植物名';
COMMENT ON COLUMN WATERING.FREQUENCY_IN_DAYS IS '日ごとの頻度';
COMMENT ON COLUMN WATERING.NEXT_DATE IS '次の日付';
COMMENT ON COLUMN WATERING.CREATED_AT IS '作成日時';
COMMENT ON COLUMN WATERING.UPDATED_AT IS '更新日時';




